fc /W .\in\1.out .\out\1.out >.\fc\1.txt 
fc /W .\in\2.out .\out\2.out >.\fc\2.txt
fc /W .\in\3.out .\out\3.out >.\fc\3.txt
fc /W .\in\4.out .\out\4.out >.\fc\4.txt
fc /W .\in\5.out .\out\5.out >.\fc\5.txt
fc /W .\in\6.out .\out\6.out >.\fc\6.txt
fc /W .\in\7.out .\out\7.out >.\fc\7.txt
fc /W .\in\8.out .\out\8.out >.\fc\8.txt
fc /W .\in\9.out .\out\9.out >.\fc\9.txt
fc /W .\in\10.out .\out\10.out >.\fc\10.txt
fc /W .\in\11.out .\out\11.out >.\fc\11.txt
fc /W .\in\12.out .\out\12.out >.\fc\12.txt
