k.exe<.\in\1.in>.\out\1.out
k.exe<.\in\2.in>.\out\2.out
k.exe<.\in\3.in>.\out\3.out
k.exe<.\in\4.in>.\out\4.out
k.exe<.\in\5.in>.\out\5.out
k.exe<.\in\6.in>.\out\6.out
k.exe<.\in\7.in>.\out\7.out
k.exe<.\in\8.in>.\out\8.out
k.exe<.\in\9.in>.\out\9.out
k.exe<.\in\10.in>.\out\10.out
k.exe<.\in\11.in>.\out\11.out
k.exe<.\in\12.in>.\out\12.out
